In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dubai_cold_coffee_spots_clean.csv")

In [3]:
df.shape

(50, 7)

In [4]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [5]:
df_areas = pd.read_csv("./dubai_areas.csv")

In [6]:
df_areas

            area_name emoji     lat     lng
0      Downtown Dubai    🏙️  25.200  55.300
1      Jumeirah Beach     🌊  25.205  55.260
2        Business Bay     🏢  25.185  55.310
3           City Walk    🛍️  25.210  55.270
4             Al Safa     🕌  25.175  55.255
5   Sheikh Zayed Road     🌆  25.220  55.290
6                DIFC     🏨  25.215  55.285
7         Zabeel Park     🌳  25.230  55.320
8             Al Wasl     🏫  25.190  55.340
9           Oud Metha     🏪  25.240  55.315
10        Al Jafiliya     🚇  25.245  55.295
11        Al Mankhool    🏘️  25.165  55.305
12            Al Bada     🌴  25.155  55.330
13              Satwa     🏬  25.175  55.275

In [7]:
df_areas["label"] = df_areas["emoji"] + " " + df_areas["area_name"]

In [8]:
df_areas

            area_name emoji     lat     lng                label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [9]:
df_areas.to_csv("dubai_areas_label.csv")

In [10]:
aa = list(df_areas["label"])

In [11]:
aa.insert(0,"select..")

In [12]:
aa

['select..',
 '🏙️ Downtown Dubai',
 '🌊 Jumeirah Beach',
 '🏢 Business Bay',
 '🛍️ City Walk',
 '🕌 Al Safa',
 '🌆 Sheikh Zayed Road',
 '🏨 DIFC',
 '🌳 Zabeel Park',
 '🏫 Al Wasl',
 '🏪 Oud Metha',
 '🚇 Al Jafiliya',
 '🏘️ Al Mankhool',
 '🌴 Al Bada',
 '🏬 Satwa']

In [13]:
df["type"].unique()

array(['cart', 'truck', 'cafe'], dtype=object)

In [14]:
df_areas

            area_name emoji     lat     lng                label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [15]:
ss = df_areas[df_areas["label"] == "🛍️ City Walk"][["lat","lng"]]
tuple(ss.iloc[0])

(25.21, 55.27)

In [16]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [17]:
df_areas

            area_name emoji     lat     lng                label
0      Downtown Dubai    🏙️  25.200  55.300    🏙️ Downtown Dubai
1      Jumeirah Beach     🌊  25.205  55.260     🌊 Jumeirah Beach
2        Business Bay     🏢  25.185  55.310       🏢 Business Bay
3           City Walk    🛍️  25.210  55.270         🛍️ City Walk
4             Al Safa     🕌  25.175  55.255            🕌 Al Safa
5   Sheikh Zayed Road     🌆  25.220  55.290  🌆 Sheikh Zayed Road
6                DIFC     🏨  25.215  55.285               🏨 DIFC
7         Zabeel Park     🌳  25.230  55.320        🌳 Zabeel Park
8             Al Wasl     🏫  25.190  55.340            🏫 Al Wasl
9           Oud Metha     🏪  25.240  55.315          🏪 Oud Metha
10        Al Jafiliya     🚇  25.245  55.295        🚇 Al Jafiliya
11        Al Mankhool    🏘️  25.165  55.305       🏘️ Al Mankhool
12            Al Bada     🌴  25.155  55.330            🌴 Al Bada
13              Satwa     🏬  25.175  55.275              🏬 Satwa

In [18]:
selected_area_df = df_areas[df_areas["label"] == "🏙️ Downtown Dubai"]
selected_area_df

        area_name emoji   lat   lng              label
0  Downtown Dubai    🏙️  25.2  55.3  🏙️ Downtown Dubai

In [19]:
lat_lng = selected_area_df[["lat","lng"]]


lat_lng
tuple(lat_lng.iloc[0])

(25.2, 55.3)

In [20]:
selected_area_df["lng"]

0    55.3
Name: lng, dtype: float64

In [21]:
df

,name,lat,lng,type,rating,opening_time,closing_time
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00

In [22]:
for data in df.iterrows():
    row = data[1]
    lat = row['lat']
    lng = row['lng']
    spot_location = (lat,lng)

    print()
    print("end row\n")

end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row


end row

In [23]:
df.loc[0]

name            Brewed Awakening
lat                    25.207773
lng                    55.290559
type                        cart
rating                       4.3
opening_time               09:00
closing_time               23:00
Name: 0, dtype: object

In [24]:
len(df)

50

In [25]:
spot_type = "cafe"

len(df[df["type"] == "cafe"])

18

In [26]:
from geopy.distance import geodesic
user_location = (25.175,55.275)
spot_location = (25.152942,55.295840)

round(geodesic(user_location,spot_location).km,2)

3.22

In [27]:
def calculate_distance(user_location,row):
    lat = row["lat"]
    lng = row["lng"]
    spot_location = (lat,lng)
    dis = geodesic(user_location,spot_location).km
    return round(dis,2)

def get_row(row):
    return calculate_distance(user_location,row)


df["distance_km"] = df.apply(get_row,axis=1)

In [28]:
df

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,6.33
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,8.54
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,8.62
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,5.23
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,3.60
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,3.69
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,4.30
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,5.94
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,8.45
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,5.21
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,7.43
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,2.29
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,4.81
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,1.88
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,2.21
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,3.55
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,6.46
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,4.18
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,7.79
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,5.26
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,3.99
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,9.53
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,4.38
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,4.80
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,7.53
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,0.48
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,6.23
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,6.98
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,8.18
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,7.15
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,8.17
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,4.17
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,9.71
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,8.08
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,2.15
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,7.70
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,0.63
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,4.32

In [29]:
from datetime import datetime

datetime.now().strftime("%H:%M")

'13:41'

In [30]:
def is_open(row):
   current_time =  datetime.now().strftime("%H:%M")
   open_time = row["opening_time"]
   close_time = row["closing_time"]

   if open_time <= current_time <= close_time:
      return "Open"
   else:
      return "Closed"

In [31]:
df.apply(is_open,axis=1)

0     Open
1     Open
2     Open
3     Open
4     Open
5     Open
6     Open
7     Open
8     Open
9     Open
10    Open
11    Open
12    Open
13    Open
14    Open
15    Open
16    Open
17    Open
18    Open
19    Open
20    Open
21    Open
22    Open
23    Open
24    Open
25    Open
26    Open
27    Open
28    Open
29    Open
30    Open
31    Open
32    Open
33    Open
34    Open
35    Open
36    Open
37    Open
38    Open
39    Open
40    Open
41    Open
42    Open
43    Open
44    Open
45    Open
46    Open
47    Open
48    Open
49    Open
dtype: object

In [32]:
df.sort_values(by="rating",ascending=False)

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,7.15
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,4.18
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,7.79
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,4.38
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,0.48
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,3.99
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,6.23
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,4.80
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,5.94
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,0.63
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,9.71
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,1.88
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,4.30
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,3.60
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,6.46
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,7.70
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,6.98
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,3.55
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,9.53
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,8.18
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,4.81
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,5.26
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,2.15
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,5.23
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,6.33
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,4.32
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,4.17
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,8.08
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,2.29
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,8.54
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,7.43
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,2.21
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,8.17
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,7.53
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,3.69
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,8.45
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,8.62
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,5.21

In [33]:
df[df["name"].str.contains('cafe',case=False)]

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63

In [34]:
df.iloc[0:2]

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56

In [35]:
df.iloc[2:4]

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62

In [36]:
df.iloc[4:6]

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23

In [37]:
df.iloc[6:8]

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48

In [38]:
# for i in range(0,len(df),2):
#     print(i,i+2)
#     df_rows = df.iloc[i:i+2]
    
small_df = df.iloc[2:4]   
small_df.iloc[0]

name            Frosty Mug
lat              25.152942
lng               55.29584
type                  cafe
rating                 4.9
opening_time         06:00
closing_time         21:00
distance_km           3.22
Name: 2, dtype: object

In [39]:
df

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,6.33
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,8.54
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,8.62
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,5.23
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,3.60
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,3.69
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,4.30
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,5.94
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,8.45
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,5.21
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,7.43
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,2.29
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,4.81
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,1.88
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,2.21
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,3.55
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,6.46
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,4.18
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,7.79
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,5.26
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,3.99
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,9.53
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,4.38
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,4.80
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,7.53
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,0.48
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,6.23
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,6.98
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,8.18
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,7.15
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,8.17
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,4.17
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,9.71
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,8.08
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,2.15
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,7.70
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,0.63
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,4.32

In [40]:
rows = df.iloc[0:2]
for ind,row in rows.iterrows():
    print(row["name"],row["type"],row["distance_km"])

Brewed Awakening cart 3.95
Chill & Spill truck 8.56

In [41]:
df.iloc[0]["name"]

'Brewed Awakening'

########### hello

In [42]:
sort_data = df.sort_values(by="distance_km")
sort_data["distance_km"].iloc[0]

np.float64(0.48)

In [43]:
df["type"].value_counts()

type
cart     22
cafe     18
truck    10
Name: count, dtype: int64

In [44]:
df

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
0,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
1,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56
2,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
3,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62
4,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
5,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23
6,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
7,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48
8,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,6.33
9,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
10,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,8.54
11,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,8.62
12,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,5.23
13,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,3.60
14,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,3.69
15,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,4.30
16,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,5.94
17,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,8.45
18,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,5.21
19,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,7.43
20,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,2.29
21,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,4.81
22,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,1.88
23,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,2.21
24,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,3.55
25,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,6.46
26,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
27,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,4.18
28,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,7.79
29,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
30,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,5.26
31,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,3.99
32,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,9.53
33,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,4.38
34,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,4.80
35,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,7.53
36,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63
37,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,0.48
38,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,6.23
39,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,6.98
40,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,8.18
41,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,7.15
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,8.17
43,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,4.17
44,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,9.71
45,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,8.08
46,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,2.15
47,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,7.70
48,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,0.63
49,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,4.32

In [45]:
df["rating"].mean()

np.float64(4.352)

In [46]:
df[df["type"] == "cafe"]["rating"].mean()

np.float64(4.355555555555555)

In [47]:
df[df["type"] == "cart"]["rating"].mean()

np.float64(4.25)

In [48]:
df[df["type"] == "truck"]["rating"].mean()

np.float64(4.57)

In [49]:
df.groupby('type')["rating"].mean()

type
cafe     4.355556
cart     4.250000
truck    4.570000
Name: rating, dtype: float64

In [50]:
df.groupby('type')["rating"].agg(['mean','sum','count'])

           mean   sum  count
type
cafe   4.355556  78.4     18
cart   4.250000  93.5     22
truck  4.570000  45.7     10

In [51]:
df["type"].value_counts()

type
cart     22
cafe     18
truck    10
Name: count, dtype: int64

In [52]:
dff = df.sort_values(by="rating",ascending=False).reset_index(drop=True)

In [53]:
dff.index = dff.index + 1

In [54]:
dff

,name,lat,lng,type,rating,opening_time,closing_time,distance_km
1,Shot Stop,25.235518,55.250343,cafe,5.0,08:00,22:00,7.15
2,Cooler Beans,25.212366,55.269280,cart,5.0,06:00,21:00,4.18
3,Espresso Express,25.178230,55.256539,cart,4.9,09:00,20:00,1.90
4,Nomad Brew,25.239391,55.306152,truck,4.9,09:00,21:00,7.79
5,The Ice Press,25.191494,55.314447,cafe,4.9,09:00,20:00,4.38
6,Iced Rush,25.172374,55.271237,truck,4.9,06:00,21:00,0.48
7,Bean Bazaar,25.198350,55.305205,truck,4.9,08:00,23:00,3.99
8,Frosty Mug,25.152942,55.295840,cafe,4.9,06:00,21:00,3.22
9,The Bean Scene,25.154320,55.340818,cafe,4.9,10:00,20:00,7.02
10,Cool Beans,25.192334,55.263833,cafe,4.8,09:00,21:00,2.23
11,Snowy Shot,25.230627,55.265882,truck,4.8,06:00,21:00,6.23
12,The Chill Spot,25.209224,55.304276,cafe,4.8,06:00,23:00,4.80
13,Arctic Brew,25.228260,55.281833,cart,4.8,09:00,22:00,5.94
14,Chill & Spill,25.248509,55.301298,truck,4.7,08:00,20:00,8.56
15,Frozen Feels,25.173230,55.280982,truck,4.7,08:00,23:00,0.63
16,Cold Culture,25.248168,55.327985,cafe,4.7,09:00,17:00,9.71
17,Caffeinated Camel,25.191213,55.269632,cart,4.7,09:00,20:00,1.88
18,Grind House,25.203164,55.304382,cart,4.6,09:00,21:00,4.30
19,Sip Stop,25.200194,55.297612,cart,4.6,08:00,22:00,3.60
20,Frost & Found,25.190576,55.336748,truck,4.6,10:00,17:00,6.46
21,Carafe Cart,25.199326,55.346555,truck,4.5,06:00,21:00,7.70
22,Café Breeze,25.150536,55.338752,cafe,4.5,07:00,22:00,6.98
23,Java Oasis,25.159588,55.305825,cart,4.5,10:00,23:00,3.55
24,Sippin’ Point,25.244079,55.331386,cart,4.4,08:00,20:00,9.53
25,Route 66 Coffee,25.216620,55.342005,cart,4.4,06:00,20:00,8.18
26,Chai Chiller,25.218065,55.269152,cafe,4.4,06:00,23:00,4.81
27,Pulse Cafe,25.182038,55.336626,cart,4.4,09:00,20:00,6.26
28,Buzz Station,25.201734,55.318113,cart,4.4,07:00,22:00,5.26
29,Perk Up Cafe,25.246448,55.272767,cart,4.3,06:00,22:00,7.92
30,Brewed Awakening,25.207773,55.290559,cart,4.3,09:00,23:00,3.95
31,The Roasted Route,25.180392,55.254501,cafe,4.3,08:00,23:00,2.15
32,Mocha Motion,25.159676,55.337032,truck,4.2,08:00,23:00,6.48
33,Bean There,25.179933,55.326601,cafe,4.2,08:00,20:00,5.23
34,Frozen Grind,25.191297,55.335197,cart,4.1,06:00,23:00,6.33
35,Iced Daily,25.213998,55.275438,cart,4.1,08:00,23:00,4.32
36,Latte Land,25.154616,55.309822,cafe,4.1,07:00,22:00,4.17
37,Brewie Louie,25.245210,55.253333,cafe,4.0,09:00,23:00,8.08
38,Brrrista,25.173272,55.252322,cafe,4.0,06:00,23:00,2.29
39,The Daily Brew,25.233261,55.330552,cart,4.0,06:00,21:00,8.54
40,Flat White Truck,25.179104,55.348576,cart,3.9,09:00,23:00,7.43
41,Desert Drip,25.161236,55.259174,cafe,3.8,06:00,23:00,2.21
42,Steamy vs Icy,25.213372,55.344224,cafe,3.8,08:00,23:00,8.17
43,Velvet Roast,25.186886,55.348506,cafe,3.7,08:00,17:00,7.53
44,Shake Shack Cafe,25.239039,55.307756,cart,3.7,06:00,23:00,7.82
45,Caffeine Cartel,25.217613,55.346531,cart,3.7,10:00,23:00,8.62
46,Iced & Easy,25.170497,55.311298,cafe,3.6,09:00,23:00,3.69
47,Cafe Mirage,25.166434,55.319951,cart,3.6,09:00,22:00,4.63
48,Quick Drip,25.243381,55.312097,cart,3.6,07:00,22:00,8.45
49,Latte on the Go,25.248106,55.304331,cart,3.5,10:00,20:00,8.62
50,Mug Life,25.220186,55.289355,truck,3.5,07:00,21:00,5.21